//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ClassLibrary1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbTranscriptsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbTranscriptsEntities object using the connection string found in the 'dbTranscriptsEntities' section of the application configuration file.
        /// </summary>
        public dbTranscriptsEntities() : base("name=dbTranscriptsEntities", "dbTranscriptsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTranscriptsEntities object.
        /// </summary>
        public dbTranscriptsEntities(string connectionString) : base(connectionString, "dbTranscriptsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTranscriptsEntities object.
        /// </summary>
        public dbTranscriptsEntities(EntityConnection connection) : base(connection, "dbTranscriptsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTransaction> tblTransactions
        {
            get
            {
                if ((_tblTransactions == null))
                {
                    _tblTransactions = base.CreateObjectSet<tblTransaction>("tblTransactions");
                }
                return _tblTransactions;
            }
        }
        private ObjectSet<tblTransaction> _tblTransactions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTransactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTransactions(tblTransaction tblTransaction)
        {
            base.AddObject("tblTransactions", tblTransaction);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTranscriptsModel", Name="tblTransaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTransaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTransaction object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="itemDescription">Initial value of the ItemDescription property.</param>
        /// <param name="itemQuantity">Initial value of the ItemQuantity property.</param>
        /// <param name="itemPrice">Initial value of the ItemPrice property.</param>
        public static tblTransaction CreatetblTransaction(global::System.Int32 id, global::System.String itemDescription, global::System.Int32 itemQuantity, global::System.Decimal itemPrice)
        {
            tblTransaction tblTransaction = new tblTransaction();
            tblTransaction.ID = id;
            tblTransaction.ItemDescription = itemDescription;
            tblTransaction.ItemQuantity = itemQuantity;
            tblTransaction.ItemPrice = itemPrice;
            return tblTransaction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemDescription
        {
            get
            {
                return _ItemDescription;
            }
            set
            {
                OnItemDescriptionChanging(value);
                ReportPropertyChanging("ItemDescription");
                _ItemDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemDescription");
                OnItemDescriptionChanged();
            }
        }
        private global::System.String _ItemDescription;
        partial void OnItemDescriptionChanging(global::System.String value);
        partial void OnItemDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemQuantity
        {
            get
            {
                return _ItemQuantity;
            }
            set
            {
                OnItemQuantityChanging(value);
                ReportPropertyChanging("ItemQuantity");
                _ItemQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemQuantity");
                OnItemQuantityChanged();
            }
        }
        private global::System.Int32 _ItemQuantity;
        partial void OnItemQuantityChanging(global::System.Int32 value);
        partial void OnItemQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ItemPrice
        {
            get
            {
                return _ItemPrice;
            }
            set
            {
                OnItemPriceChanging(value);
                ReportPropertyChanging("ItemPrice");
                _ItemPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemPrice");
                OnItemPriceChanged();
            }
        }
        private global::System.Decimal _ItemPrice;
        partial void OnItemPriceChanging(global::System.Decimal value);
        partial void OnItemPriceChanged();

        #endregion
    
    }

    #endregion
    
}
