//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ClassLibrary1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbTranscriptsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbTranscriptsEntities object using the connection string found in the 'dbTranscriptsEntities' section of the application configuration file.
        /// </summary>
        public dbTranscriptsEntities() : base("name=dbTranscriptsEntities", "dbTranscriptsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTranscriptsEntities object.
        /// </summary>
        public dbTranscriptsEntities(string connectionString) : base(connectionString, "dbTranscriptsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTranscriptsEntities object.
        /// </summary>
        public dbTranscriptsEntities(EntityConnection connection) : base(connection, "dbTranscriptsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTranscript> tblTranscripts
        {
            get
            {
                if ((_tblTranscripts == null))
                {
                    _tblTranscripts = base.CreateObjectSet<tblTranscript>("tblTranscripts");
                }
                return _tblTranscripts;
            }
        }
        private ObjectSet<tblTranscript> _tblTranscripts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTranscripts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTranscripts(tblTranscript tblTranscript)
        {
            base.AddObject("tblTranscripts", tblTranscript);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTranscriptsModel", Name="tblTranscript")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTranscript : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTranscript object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="className">Initial value of the ClassName property.</param>
        /// <param name="classCreditHours">Initial value of the ClassCreditHours property.</param>
        /// <param name="classGrade">Initial value of the ClassGrade property.</param>
        public static tblTranscript CreatetblTranscript(global::System.Int32 id, global::System.String className, global::System.Int32 classCreditHours, global::System.String classGrade)
        {
            tblTranscript tblTranscript = new tblTranscript();
            tblTranscript.ID = id;
            tblTranscript.ClassName = className;
            tblTranscript.ClassCreditHours = classCreditHours;
            tblTranscript.ClassGrade = classGrade;
            return tblTranscript;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassName
        {
            get
            {
                return _ClassName;
            }
            set
            {
                OnClassNameChanging(value);
                ReportPropertyChanging("ClassName");
                _ClassName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClassName");
                OnClassNameChanged();
            }
        }
        private global::System.String _ClassName;
        partial void OnClassNameChanging(global::System.String value);
        partial void OnClassNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassCreditHours
        {
            get
            {
                return _ClassCreditHours;
            }
            set
            {
                OnClassCreditHoursChanging(value);
                ReportPropertyChanging("ClassCreditHours");
                _ClassCreditHours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassCreditHours");
                OnClassCreditHoursChanged();
            }
        }
        private global::System.Int32 _ClassCreditHours;
        partial void OnClassCreditHoursChanging(global::System.Int32 value);
        partial void OnClassCreditHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassGrade
        {
            get
            {
                return _ClassGrade;
            }
            set
            {
                OnClassGradeChanging(value);
                ReportPropertyChanging("ClassGrade");
                _ClassGrade = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClassGrade");
                OnClassGradeChanged();
            }
        }
        private global::System.String _ClassGrade;
        partial void OnClassGradeChanging(global::System.String value);
        partial void OnClassGradeChanged();

        #endregion
    
    }

    #endregion
    
}
